name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 -m build
      - run: |
          twine upload -u __token__ -p ${{ secrets.PYPI_UPLOAD_PSEUDOCERASTES_TWINE_TOKEN }} dist/*